apiVersion: v1
kind: ConfigMap
metadata:
  name: nameserver-conf
  labels:
    {{- include "rocketmq-nameserver.labels" . | nindent 4 }}
data:
  namesrv.p: |
    listenPort={{ include "rocketmq-nameserver.port" . }}
    {{ .Values.nameserver.configmap | indent 4 | trim }}
